### ISSUE TITLE
fail pip install

### ISSUE THREAD

**Issue by Macsim2** [csukuangfj/kaldifeat#104]
Hi, I trying to install kaldifeat using pip in ubuntu 22.04, kernel 5.15.0-113-generic
But I face the errors
/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:105:27: error: cannot convert ‘const torch::enumtype::kFanIn’ to ‘int’
        105 |     init::kaiming_uniform_(                                                                                                                                                     
            |     ~~~~~~~~~~~~~~~~~~~~~~^                                                                                                                                                     
            |                           |                                                                                                                                                     
            |                           const torch::enumtype::kFanIn                          
        106 |         weight,                                                                                                                                                                 
            |         ~~~~~~~                                                                  
        107 |         /*a=*/std::sqrt(5)); // NOLINT(cppcoreguidelines-avoid-magic-numbers)                                                                                                   
            |         ~~~~~~~~~~~~~~~~~~~                                                                                                                       
/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:105:27: error: cannot convert ‘const torch::enumtype::kFanIn’ to ‘int’             
        105 |     init::kaiming_uniform_(                                                                                                                                                     
            |     ~~~~~~~~~~~~~~~~~~~~~~^                                                                                                                                                     
            |                           |                                                                                                                                                     
            |                           const torch::enumtype::kFanIn                                                                                                                         
        106 |         weight,                                                                                                                                                                 
            |         ~~~~~~~                                                                                                                                                                 
        107 |         /*a=*/std::sqrt(5)); // NOLINT(cppcoreguidelines-avoid-magic-numbers)                                                                                                   
            |         ~~~~~~~~~~~~~~~~~~~                                               
How can I do address the problem..? anyone who know this issue help me.?

My pip freeze are  
""
astunparse==1.6.3
blinker==1.4             
cryptography==3.4.8
dbus-python==1.2.18 
distlib==0.3.8
distro==1.7.0
dm-tree==0.1.8
filelock==3.15.4 
fsspec==2024.6.1
gast==0.6.0              
httplib2==0.20.2   
importlib-metadata==4.6.4
jeepney==0.7.1
Jinja2==3.1.4
keyring==23.5.0
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
MarkupSafe==2.1.5
more-itertools==8.10.0
mpmath==1.3.0
networkx==3.3
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-dali-cuda120==1.38.0
nvidia-nccl-cu12==2.20.5
nvidia-nvimgcodec-cu12==0.2.0.7
nvidia-nvjitlink-cu12==12.6.20
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.0
onnx==1.16.2
platformdirs==4.2.2
protobuf==5.27.3
PyGObject==3.42.1
PyJWT==2.3.0
pyparsing==2.4.7
python-apt==2.4.0+ubuntu3
PyYAML==6.0.2
SecretStorage==3.3.1
six==1.16.0
sympy==1.13.1
torch==2.4.0
torchaudio==2.4.0
triton==3.0.0
typing_extensions==4.12.2
virtualenv==20.26.3
wadllib==1.3.6
zipp==1.0.0
"""

**Comment by csukuangfj** [comment]
Please tell us the command you used to install kaldifeat.

**Comment by csukuangfj** [comment]
Have you read
https://csukuangfj.github.io/kaldifeat/installation/from_wheels.html
?

**Comment by Macsim2** [comment]
my pip install command is 
"pip install kaldifeat"

and sorry, I didn't catch that https://csukuangfj.github.io/kaldifeat/installation/from_wheels.html 
should I follow the description ?

**Comment by csukuangfj** [comment]
> should I follow the description ?

Yes. please follow the doc

**Comment by csukuangfj** [comment]
Just updated readme to inform users to not use `pip install kaldifeat`.

**Comment by Macsim2** [comment]
Oh I really appreciate it @csukuangfj 
The docs work for me.
