### ISSUE TITLE
Whisper fbank features vs Kaldi fbank features – Clarification Needed

### ISSUE THREAD

**Issue by sangeet2020** [csukuangfj/kaldifeat#111]
Hi,
I would like to understand the differences between Whisper's fbank features and Kaldi's fbank features? I get that conceptually both features are derived from Mel-filterbank energies, but then what makes them different?

thank you.

**Comment by csukuangfj** [comment]
There are many many differences.

For instance, the function for converting hz to mel is different.

Please have a look at the code to find them out by yourself.

**Comment by sangeet2020** [comment]
I went through it, and indeed there were several minute differences:
- filterbank size (80 in kaldi vs 123 in whisper v3)
- fft size (dynamically computed in kaldi, while whisper uses 400)
- window function (povey in kaldi vs hann in whisper)
- normalization (in whisper log-mel values are normalized to [-4, 0])
- difference in the data padding step.

would there be more?

**Comment by csukuangfj** [comment]
Is there pre-emphasis?

How is the filter bank matrix computed?

**Comment by sangeet2020** [comment]
oh yeah, pre-emphasis, missed writing that.
>> How is the filter bank matrix computed?
kaldi uses dot product between spectrum magnitude and mel_banks, while whisper uses matrix multiplication between stft magnitudes and mel_filters.

**Comment by csukuangfj** [comment]
I am afraid you don't know the details of mel.filter bank matrix.

**Comment by csukuangfj** [comment]
or you don know how the matrix is  computed.

**Comment by sangeet2020** [comment]
Whisper uses librosa.filters.mel() to generate mel filter bank matrix, while kaldifeat fbank computer mel filter banks by creating triangular filters and applying them to the FFT bins.
