### ISSUE TITLE
Ubuntu/Debian `pip install kaldifeat`: cannot find CUDNN

### ISSUE THREAD

**Issue by pzelasko** [csukuangfj/kaldifeat#12]
either doing `pip install kaldifeat`, or cloning source and doing `python setup.py install`, yields the following message:

```
...
-- Found CUDA: /usr/local/cuda (found version "10.2")
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH CUDNN_INCLUDE_PATH)
CMake Warning at /home/pzelasko/miniconda3/envs/lhotse/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:109 (message):
  Caffe2: Cannot find cuDNN library.  Turning the option off
Call Stack (most recent call first):
  /home/pzelasko/miniconda3/envs/lhotse/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/pzelasko/miniconda3/envs/lhotse/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  cmake/torch.cmake:13 (find_package)
  CMakeLists.txt:41 (include)
```

I am able to build it by doing this:

```
<inside sources root>
mkdir build
cd build
cmake .. -DCUDNN_LIBRARY_PATH="/home/pzelasko/miniconda3/envs/lhotse/lib" -DCUDNN_INCLUDE_PATH="/home/pzelasko/miniconda3/envs/lhotse/include"
```

But there seems to be no way to pass these values through env vars when doing `pip install kaldifeat`.

**Comment by csukuangfj** [comment]
> But there seems to be no way to pass these values through env vars when doing pip install kaldifeat.

There are some ways to pass these env vars to it, either using `pip install` or using `python3 setup.py install`.


Will propose a fix.

**Comment by csukuangfj** [comment]
The code is in
https://github.com/csukuangfj/kaldifeat/blob/3de5b99c302491a60e2a7bb19c96ff66273d585e/cmake/cmake_extension.py#L59

https://github.com/csukuangfj/kaldifeat/blob/3de5b99c302491a60e2a7bb19c96ff66273d585e/cmake/cmake_extension.py#L63-L64

https://github.com/csukuangfj/kaldifeat/blob/3de5b99c302491a60e2a7bb19c96ff66273d585e/cmake/cmake_extension.py#L77

**Comment by WangHelin1997** [comment]
The same error and solved with it. Thanks!
