### ISSUE TITLE
Support other sample rate?

### ISSUE THREAD

**Issue by day9011** [csukuangfj/kaldifeat#16]

**Comment by csukuangfj** [comment]
Yes, that is already supported. 

For example, if you use `FbankOptions`, please see

https://github.com/csukuangfj/kaldifeat/blob/ec66d87faef088c45d6ce5498a7f0efe3a059afe/kaldifeat/python/tests/test_fbank_options.py#L12-L13

You can find usage of options for other feature types in https://github.com/csukuangfj/kaldifeat/tree/master/kaldifeat/python/tests

**Comment by day9011** [comment]
Thanks
