### ISSUE TITLE
CPU only version

### ISSUE THREAD

**Issue by day9011** [csukuangfj/kaldifeat#19]
Is there any document for installing a cpu only version?

**Comment by csukuangfj** [comment]
Yes.

The steps are:

1. Install a CPU-only version of PyTorch
2. Install kaldifeat from source or use `pip install kaldifeat` (see README.md, https://github.com/csukuangfj/kaldifeat)

NOTE: You cannot use conda to install a CPU-only version of kaldifeat. 

---

The most important step is `step 1`. You have to install a CPU-only version of PyTorch.
