### ISSUE TITLE
Taking forever to install kaldifeat

### ISSUE THREAD

**Issue by huangruizhe** [csukuangfj/kaldifeat#45]
Hello, I am trying to install kaldifeat following the instructions in the doc, with this command:
`pip install --verbose kaldifeat`

It's been ~8 hours now but it seems the program got stuck at this place:
![image](https://user-images.githubusercontent.com/28626513/182012805-e26159bf-d14a-47ef-8db8-1359b5694056.png)

I was wondering if this is normal or if perhaps I should ask for some help now. Thank you!

**Comment by csukuangfj** [comment]
Could you press `ctrl + c` and see whether there are any more logs?

It is not normal that it would take so long to install.

**Comment by huangruizhe** [comment]
Thanks, here is the result:

![image](https://user-images.githubusercontent.com/28626513/182013653-b3d37f6a-08e8-4c18-a1ec-5bd51aef911d.png)

**Comment by csukuangfj** [comment]
Could you use
```bash
git clone https://github.com/csukuangfj/kaldifeat/
cd kaldifeat
mkdir build
cd build
cmake ..
make -j
export PYTHONPATH=$PWD/../kaldifeat/python:$PWD/lib:$PYTHONPATH

cd $HOME
python3 -c "import kaldifeat; print(kaldifeat.__file__)"
```

**Comment by huangruizhe** [comment]
Thanks for the detailed instructions! I will try now.

**Comment by huangruizhe** [comment]
After a while, it got stuck at the same place again (maybe 20+ minutes now):

![image](https://user-images.githubusercontent.com/28626513/182014553-08ea47ae-8761-4cde-bb4b-896ac1833e4e.png)

Is it related to some failed tests as shown on the screenshot?

**Comment by csukuangfj** [comment]
I guess it probably has something with your NFS.

Could you try https://csukuangfj.github.io/kaldifeat/installation.html#install-kaldifeat-from-conda-only-for-linux
to instal kaldifeat using `conda install`.

I have no idea about how to fix your issue.

**Comment by huangruizhe** [comment]
Ok, I see. I tried installing it with conda earlier, but conda is very slow in figuring out package dependencies.. Then I tried pip, and installing from src as you suggested.
I will ask others if they have successfully installed kaldifeat on our system. Will update you if there is a solution.

**Comment by csukuangfj** [comment]
> conda is very slow in figuring out package dependencies

That should not be the case. There might be something wrong with your system.

---

> Then I tried pip,

That is also installing from source.

---

> I will ask others if they have successfully installed kaldifeat on our system. 

Yes, that is a good idea.

**Comment by pzelasko** [comment]
If conda is too slow, you can try mamba, it is the same as conda, but resolves dependencies much faster. 

https://mamba.readthedocs.io/en/latest/installation.html

**Comment by huangruizhe** [comment]
Thanks, @csukuangfj and @pzelasko for the suggestions!
Finally, it turns out it is the problem of the system. It is very "lucky" that the node that I usually ssh to has something wrong. I couldn't even install mamba or a new conda -- which takes a forever long time too.
When I ssh to another node, the problem is resolved. I can now install kaldifeat with conda.
It is also a good time to try mamba.

**Comment by csukuangfj** [comment]
Nice to hear that you fix it.
