### ISSUE TITLE
Centos: ImportError: libmkl_intel_ilp64.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PPGGG** [csukuangfj/kaldifeat#46]
I installed `kaldifeat` by using `python setup.py install`. But it came out the follow errors:

`ImportError: libmkl_intel_ilp64.so.2: cannot open shared object file: No such file or directory`

But i do found `libmkl_intel_ilp64.so` in the environment lib directory.

**Comment by csukuangfj** [comment]
> But i do found libmkl_intel_ilp64.so in the environment lib directory.

Could you use
```
export LD_LIBRARY_PATH=/path/to/the/dir/that/contains/libmkl_intel_ilp64.so:$LD_LIBRARY_PATH
```

and then run again `python3 -c "import kaldifeat"`

**Comment by PPGGG** [comment]
`export LD_LIBRARY_PATH=/home/Dell/anaconda3/envs/streaming_asr/lib/libmkl_intel_ilp64.so:$LD_LIBRARY_PATH`

Then i run `python -c "import kaldifeat"`, still get the error.

```
python3 -c "import kaldifeat"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/kaldifeat-1.17-py3.8-linux-x86_64.egg/kaldifeat/__init__.py", line 11, in <module>
    from _kaldifeat import (
ImportError: libmkl_intel_ilp64.so.2: cannot open shared object file: No such file or directory
```

**Comment by csukuangfj** [comment]
```
export LD_LIBRARY_PATH=/home/Dell/anaconda3/envs/streaming_asr/lib/libmkl_intel_ilp64.so:$LD_LIBRARY_PATH
```

Please use
```
export LD_LIBRARY_PATH=/home/Dell/anaconda3/envs/streaming_asr/lib:$LD_LIBRARY_PATH
```

**Comment by PPGGG** [comment]
> ```
> export LD_LIBRARY_PATH=/home/Dell/anaconda3/envs/streaming_asr/lib/libmkl_intel_ilp64.so:$LD_LIBRARY_PATH
> ```
> 
> Please use
> 
> ```
> export LD_LIBRARY_PATH=/home/Dell/anaconda3/envs/streaming_asr/lib:$LD_LIBRARY_PATH
> ```

Still get the error. Should i reinstall kaldifeat ?

**Comment by csukuangfj** [comment]
Could you find the file `libmkl_intel_ilp64.so.2`?

How did you install kaldifeat? Did you install it with `conda install`? 

If yes, I suggest you installing kaldifeat from source, i.e., use
```
conda remove kaldifeat
pip install kaldifeat
```

**Comment by csukuangfj** [comment]
@PPGGG 

please have a look at https://github.com/csukuangfj/kaldifeat/issues/10#issuecomment-1195137482
and check that you have set `LD_LIBRARY_PATH` correctly.

**Comment by PPGGG** [comment]
> conda remove kaldifeat

I tried to install kaldifeat from source, but it came out the following errors:

```
ImportError: kaldifeat was built using PyTorch 1.11.0
But you are using PyTorch 1.10.1 to run it
```

Then i install kaldifeat from source `python setup.py install`, then it came out the following errors:

`ImportError: libmkl_intel_ilp64.so.2: cannot open shared object file: No such file or directory`

**Comment by PPGGG** [comment]
> libmkl_intel_ilp64.so.2

I could not find this file.

**Comment by csukuangfj** [comment]
> I could not find this file.

What is the command you are using to find that file?

**Comment by PPGGG** [comment]
I just enter `/home/Dell/anaconda3/envs/streaming_asr/lib` and lookup for it.

**Comment by csukuangfj** [comment]
> I tried to install kaldifeat from pip, but it came out the following errors:
>
> ImportError: kaldifeat was built using PyTorch 1.11.0
But you are using PyTorch 1.10.1 to run it

That should not happen if you don't change the version of PyTorch after installing kaldifeat.

---

Could you use
```
find /home/Dell/anaconda3/envs -name "libmkl_intel*"

**Comment by csukuangfj** [comment]
I think the dependency is from PyTorch.

You said that you first tried to install kaldifeat with `pip install` and then you try to install it with `python3 setup.py install`.

Have you uninstalled `kaldifeat` before you try to use `python3 setup.py install`?

What is the output of
```
ls -lh /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/*kaldifeat*

ls -lh /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/*kaldifeat*/*

**Comment by PPGGG** [comment]
> I think the dependency is from PyTorch.
> 
> You said that you first tried to install kaldifeat with `pip install` and then you try to install it with `python3 setup.py install`.
> 
> Have you uninstalled `kaldifeat` before you try to use `python3 setup.py install`?
> 
> What is the output of
> 
> ```
> ls -lh /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/*kaldifeat*
> 
> ls -lh /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/*kaldifeat*/*
> ```


Yes, i uninstalled `kaldifeat` before i try to use `python3 setup.py install`
```
ls -lh /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/*kaldifeat*
-rwxrwxrwx 1 Dell Dell 327K Aug  1 14:16 /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/_kaldifeat.cpython-38-x86_64-linux-gnu.so
-rwxrwxrwx 1 Dell Dell 233K Aug  1 14:16 /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/libkaldifeat_core.so

/home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/kaldifeat-1.17-py3.8-linux-x86_64.egg:
total 588K
drwxrwxr-x 2 Dell Dell  161 Aug  1 14:32 EGG-INFO
drwxrwxr-x 2 Dell Dell   47 Aug  1 14:32 __pycache__
-rwxr-xr-x 1 Dell Dell 357K Aug  1 14:32 _kaldifeat.cpython-38-x86_64-linux-gnu.so
-rw-rw-r-- 1 Dell Dell  435 Aug  1 14:32 _kaldifeat.py
drwxrwxr-x 3 Dell Dell  226 Aug  1 14:32 kaldifeat
-rwxr-xr-x 1 Dell Dell 223K Aug  1 14:32 libkaldifeat_core.so
```

```
ls -lh /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/kaldifeat/*
-rwxr-xr-x 1 Dell Dell 357K Aug  1 14:32 /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/kaldifeat-1.17-py3.8-linux-x86_64.egg/kaldifeat.cpython-38-x86_64-linux-gnu.so
-rw-rw-r-- 1 Dell Dell  435 Aug  1 14:32 /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/kaldifeat-1.17-py3.8-linux-x86_64.egg/kaldifeat.py
-rwxr-xr-x 1 Dell Dell 223K Aug  1 14:32 /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/kaldifeat-1.17-py3.8-linux-x86_64.egg/libkaldifeat_core.so

/home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/kaldifeat-1.17-py3.8-linux-x86_64.egg/EGG-INFO:
total 32K
-rw-rw-r-- 1 Dell Dell 8.7K Aug  1 14:32 PKG-INFO
-rw-rw-r-- 1 Dell Dell 3.9K Aug  1 14:32 SOURCES.txt
-rw-rw-r-- 1 Dell Dell    1 Aug  1 14:32 dependency_links.txt
-rw-rw-r-- 1 Dell Dell   63 Aug  1 14:32 native_libs.txt
-rw-rw-r-- 1 Dell Dell    1 Aug  1 14:32 not-zip-safe
-rw-rw-r-- 1 Dell Dell   21 Aug  1 14:32 top_level.txt

/home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/kaldifeat-1.17-py3.8-linux-x86_64.egg/pycache:
total 4.0K
-rw-rw-r-- 1 Dell Dell 658 Aug  1 14:32 _kaldifeat.cpython-38.pyc

/home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/kaldifeat-1.17-py3.8-linux-x86_64.egg/kaldifeat:
total 36K
-rw-rw-r-- 1 Dell Dell  714 Aug  1 14:32 init.py
drwxrwxr-x 2 Dell Dell  299 Aug  1 14:32 pycache
-rw-rw-r-- 1 Dell Dell  668 Aug  1 14:32 fbank.py
-rw-rw-r-- 1 Dell Dell  660 Aug  1 14:32 mfcc.py
-rw-rw-r-- 1 Dell Dell 5.7K Aug  1 14:32 offline_feature.py
-rw-rw-r-- 1 Dell Dell 3.4K Aug  1 14:32 online_feature.py
-rw-rw-r-- 1 Dell Dell  652 Aug  1 14:32 plp.py
-rw-rw-r-- 1 Dell Dell  314 Aug  1 14:32 spectrogram.py
-rw-rw-r-- 1 Dell Dell  342 Aug  1 14:32 torch_version.py

```

**Comment by csukuangfj** [comment]
> Yes, i uninstalled kaldifeat before i try to use python3 setup.py install

You did not uninstall it correctly.

Please remove the following files:
```
-rwxrwxrwx 1 Dell Dell 327K Aug  1 14:16 /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/_kaldifeat.cpython-38-x86_64-linux-gnu.so
-rwxrwxrwx 1 Dell Dell 233K Aug  1 14:16 /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/libkaldifeat_core.so
```

When you uninstall `kaldifeat` next time, please use
```
pip uninstall kaldifeat # if you installed kaldifeat with `pip install` or `python3 setup.py install`.
# or
conda remove kaldifeat # if you installed kaldifeat with "conda install"
```

**Comment by PPGGG** [comment]
> 

You are so awesome. It works perfect now. @csukuangfj
