### ISSUE TITLE
_kaldifeat.get_strided  got error

### ISSUE THREAD

**Issue by taotaoyuhust** [csukuangfj/kaldifeat#50]
hi, 
when i run a pretrained model under icefall, i used this command :
python ./pruned_transducer_stateless2/pretrained.py --decoding-method greedy_search --lang-dir ./luomingshuang_pruned_transducer_stateless2/data/lang_char --max-sym-per-frame 1 --sample-rate 16000 --checkpoint ./luomingshuang_pruned_transducer_stateless2/exp/pretrained_epoch_10_avg_2.pt ./luomingshuang_pruned_transducer_stateless2/test_wavs/VID_175648.wav

and i got this error:
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\kaldifeat-1.18-py3.6-win-amd64.egg\kaldifeat\offline_feature.py", line 155, in convert_samples_to_frames
    return _kaldifeat.get_strided(wave, self.opts.frame_opts)
RuntimeError: setStorage: sizes [1504, 400], strides [320, 2], storage offset 0, and itemsize 4 requiring a storage size of 1927036 are out of bounds for storage of size 963520

i searched everywhere and got no idea, please help, thank you!

**Comment by csukuangfj** [comment]
What is the output of 
```
soxi ./luomingshuang_pruned_transducer_stateless2/test_wavs/VID_175648.wav
```
?

**Comment by taotaoyuhust** [comment]
Thanks for reply ,the output is like this :

sox --i  .\test_wavs\VID_175648.wav

Input File     : '.\test_wavs\VID_175648.wav'
Channels       : 2
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:15.04 = 240640 samples ~ 1128 CDDA sectors
File Size      : 963k
Bit Rate       : 512k
Sample Encoding: 16-bit Signed Integer PCM

**Comment by csukuangfj** [comment]
could you first covert it to a wav with a single channel and try again?

**Comment by taotaoyuhust** [comment]
Thank you very much!  It works after i converted it to a single channel wav ! Great

>sox.exe .\test_wavs\VID_175648.wav -c 1 .\test_wavs\VID_175648_new.wav 
>sox.exe --i .\test_wavs\VID_175648_new.wav
wav info like this 
Input File     : '.\test_wavs\VID_175648_new.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:15.04 = 240640 samples ~ 1128 CDDA sectors
File Size      : 481k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM
