### ISSUE TITLE
/lib64/libm.so.6: version `GLIBC_2.27' not found (required by python3.7/site-packages/libkaldifeat_core.so

### ISSUE THREAD

**Issue by maxandchen** [csukuangfj/kaldifeat#53]
>>> import kaldifeat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cyn244124/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.7/site-packages/kaldifeat/__init__.py", line 2, in <module>
    from _kaldifeat import FbankOptions, FrameExtractionOptions, MelBanksOptions
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /lib/python3.7/site-packages/libkaldifeat_core.so)

**Comment by csukuangfj** [comment]
How did you install kaldifeat?
Did you use `conda install`?

**Comment by maxandchen** [comment]
pip install kaldifeat

**Comment by csukuangfj** [comment]
> /home/cyn244124/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.7/site-packages/kaldifeat/init.py

> lib/python3.7/site-packages/libkaldifeat_core.so

Have you tried to install kaldifeat with `conda install` before?

The logs show that you have two places with kaldifeat installed.

Please uninstall the one from your conda env.
