### ISSUE TITLE
源码安装出现错误

### ISSUE THREAD

**Issue by Text2-m** [csukuangfj/kaldifeat#65]
<img width="1395" alt="截屏2023-02-07 17 27 30" src="https://user-images.githubusercontent.com/37999223/217207290-d8318e47-80be-4d5d-8271-e888d9a7bf01.png">

**Comment by csukuangfj** [comment]
需要支持 c++14 的 gcc.

你目前的 gcc 版本是多少？

如果你是自己从源码安装的 gcc, 请参考下面的文档，设置环境变量

https://k2-fsa.github.io/k2/installation/faqs.html#error-c-14-or-later-compatible-compiler-is-required-to-use-aten

---

切记：设置好环境变量后，删除 build 目录，再重试.

**Comment by csukuangfj** [comment]
@Text2-m  请问解决了没有？

https://csukuangfj.github.io/kaldifeat/cpu.html

https://csukuangfj.github.io/kaldifeat/cuda.html

上述两个网页包含预编译的 whl.
