### ISSUE TITLE
Ubuntu 22.04 pip install kaldifeat: cannot find CUDNN

### ISSUE THREAD

**Issue by ravi-mr** [csukuangfj/kaldifeat#68]
@csukuangfj 

Despite any flags, compiling kaldifeat could not find CUDNN,

`  -- Caffe2: CUDA detected: 11.7

  -- Caffe2: CUDA nvcc is: /usr/local/cuda-11.7/bin/nvcc

  -- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.7

  -- Caffe2: Header version is: 11.7

  -- /usr/local/cuda-11.7/lib64/libnvrtc.so shorthash is d833c4f3

  -- **USE_CUDNN is set to 0. Compiling without cuDNN support**
 `
Following https://github.com/csukuangfj/kaldifeat/issues/12,  I tried passing in

`export KALDIFEAT_CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DCUDNN_LIBRARY_PATH=/usr/local/cuda-11.7/lib64/libcudnn.so -DCUDNN_INCLUDE_PATH=/usr/local/cuda-11.7/include -DUSE_CUDNN=1"
`

what is the impact of not having kaldifeat compiled with cudnn?
any other suggestion for compiling kaldifeat with cudnn?

**Comment by csukuangfj** [comment]
There are two fixes:

1. If you only want a CPU version of kaldifeat, please install a CPU version of PyTorch, which does not need cudnn at all.

2. Please follow 

https://k2-fsa.github.io/k2/installation/cuda-cudnn.html

to install cudnn.

**Comment by ravi-mr** [comment]
adapted the same as given at https://k2-fsa.github.io/k2/installation/cuda-cudnn.html#cuda-11-7,

`-- /usr/local/cuda-11.7.1/lib64/libnvrtc.so shorthash is 581f1f99
-- **USE_CUDNN is set to 0**. Compiling without cuDNN support
-- Autodetected CUDA architecture(s):  8.6
-- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
CMake Warning at /venv/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /venv/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  cmake/torch.cmake:14 (find_package)
  CMakeLists.txt:59 (include)


-- Found Torch: /venv/lib/python3.8/site-packages/torch/lib/libtorch.so  
-- PyTorch version: 2.0.0+cu117
`
still USE_CUDNN is not getting set to 1?

**Comment by csukuangfj** [comment]
That's a warning, not an error.

Is there still anything stopping you from installing kaldifeat?

**Comment by ravi-mr** [comment]
I could install kaldifeat.
Was thinking if USE_CUDNN sets to 1, kaldifeat extraction can be faster in respective contexts.
Does linking kaldifeat with cuda_dnn increase any speed?

**Comment by csukuangfj** [comment]
> I could install kaldifeat.
> 
> Was thinking if USE_CUDNN sets to 1, kaldifeat extraction can be faster in respective contexts.
> 
> Does linking kaldifeat with cuda_dnn increase any speed?

USE_CUDNN exists only in torch 2.0.0 

We don't have much experience about it now.

Maybe you could try torch < 2.0.0

**Comment by ravi-mr** [comment]
True.
