### ISSUE TITLE
Error when building kaldifeat from source

### ISSUE THREAD

**Issue by ZihanLiao** [csukuangfj/kaldifeat#70]
When I'm building from source, I met the following error.
-- C++ Standard version: 14
-- Downloading pybind11 from https://github.com/pybind/pybind11/archive/5bc0943ed96836f46489f53961f6c438d2935357.zip
-- pybind11 is downloaded to /home/share_ssd_data/env/liaozihan/kaldifeat/build/_deps/pybind11-src
-- pybind11 v2.11.0 dev1
-- Python executable: /home/liaozihan1/anaconda3/envs/k2/bin/python
-- TORCH_DIR: /home/liaozihan1/anaconda3/envs/k2/lib/python3.8/site-packages/torch
-- Caffe2: CUDA detected: 11.6
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 11.6
-- Found CUDNN: /home/share_ssd_data/env/liaozihan/cuda-11.0.3/lib64/libcudnn.so  
-- Found cuDNN: v8.0.5  (include: /home/share_ssd_data/env/liaozihan/cuda-11.0.3/include, library: /home/share_ssd_data/env/liaozihan/cuda-11.0.3/lib64/libcudnn.so)
-- /usr/local/cuda/lib64/libnvrtc.so shorthash is 4dd39364
-- Autodetected CUDA architecture(s):  8.0 8.0 8.0 8.0 8.0 8.0 8.0 8.0
-- Added CUDA NVCC flags for: -gencode;arch=compute_80,code=sm_80
CMake Warning at /home/liaozihan1/anaconda3/envs/k2/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /home/liaozihan1/anaconda3/envs/k2/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  cmake/torch.cmake:14 (find_package)
  CMakeLists.txt:59 (include)

-- Found Torch: /home/liaozihan1/anaconda3/envs/k2/lib/python3.8/site-packages/torch/lib/libtorch.so  
-- PyTorch version: 1.13.0
-- Downloading googletest from https://github.com/google/googletest/archive/refs/tags/v1.13.0.tar.gz
-- googletest is downloaded to /home/share_ssd_data/env/liaozihan/kaldifeat/build/_deps/googletest-src
-- googletest's binary dir is /home/share_ssd_data/env/liaozihan/kaldifeat/build/_deps/googletest-build
-- Found Python: /home/liaozihan1/anaconda3/envs/k2/bin/python3.8 (found version "3.8.16") found components: Interpreter 
-- CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0
-- CMAKE_INSTALL_PREFIX: /usr/local
-- All headers: /home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/feature-common-inl.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/feature-common.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/feature-fbank.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/feature-functions.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/feature-mfcc.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/feature-plp.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/feature-spectrogram.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/feature-window.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/log.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/matrix-functions.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/mel-computations.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/online-feature-itf.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/online-feature.h;/home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/csrc/pitch-functions.h
-- Configuring done (10.5s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY (ADVANCED)
    linked by target "_kaldifeat" in directory /home/share_ssd_data/env/liaozihan/kaldifeat/kaldifeat/python/csrc

**CMake Error in kaldifeat/python/csrc/CMakeLists.txt:
  Imported target "pybind11::module" includes non-existent path

    /opt/anaconda1anaconda2anaconda3/include/python3.8

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.**

-- Generating done (0.2s)

Buding command
`mkdir build
 cd build
 cmake -DCUDNN_LIBRARY_PATH=/path/to/my/libcudnn.so -DCUDNN_INCLUDE_PATH=/path/to/my/cuda/include -DCMAKE_BUILD_TYPE=Release .. 
`

**Comment by csukuangfj** [comment]
Could you remove
```
/home/share_ssd_data/env/liaozihan/kaldifeat/build
```
and try again?

Please post
```
/home/share_ssd_data/env/liaozihan/kaldifeat/build/CMakeCache.txt
```
for you next run.

**Comment by ZihanLiao** [comment]
Solved this problem by adding `-DPYTHON_INCLUDE_DIRS=/xxx/xxx/python3.8 -Dpybind11_INCLUDE_DIRS=/xxx/xxx/pybind11-src/include -DPYTHON_LIBRARY=/xxx/xxx/lib/python3.8/` to the cmake options.
Many thanks!
