### ISSUE TITLE
请问目前支持Pitch提取吗

### ISSUE THREAD

**Issue by cantabile-kwok** [csukuangfj/kaldifeat#78]
您好！我看README中提到“We will implement other types of features, e.g., Pitch, ivector, etc, soon.”，请问目前是否还不支持Kaldi中的pitch提取命令？具体来说是`compute-kaldi-pitch-feats`这个命令。
如果这个工具目前不支持，是否有别的工具能够代替kaldi完成呢？
谢谢！

**Comment by csukuangfj** [comment]
> 请问目前是否还不支持Kaldi中的pitch提取命令

还没实现完。现在没动力去实现这个了，主要是没需求。



> 如果这个工具目前不支持，是否有别的工具能够代替kaldi完成呢？


不好意思，我不清楚这个。
