### ISSUE TITLE
FbankOpts (and others) conversion to/from dict

### ISSUE THREAD

**Issue by pzelasko** [csukuangfj/kaldifeat#8]
Would it be possible to add a conversion mechanism for the `Opts` classes to/from dict? It would make it much easier for me to integrate kaldifeat in Lhotse. I'm using dataclasses for configuration of all feature extractors, like this:

https://github.com/lhotse-speech/lhotse/blob/f5bd2063291b7d789d4b8a2a50396d2ffa76eb2c/lhotse/features/fbank.py#L9-L31

Example API could look like this:

```python
# Read a dict
config = {"frame_shift": 0.012, "use_energy": True}
extractor = kaldifeat.Fbank(kaldifeat.FbankOptions.from_dict(config))

# Store to a dict
config2 = extractor.opts.to_dict()
# config2 = {... a list of all settings ...}
```

**Comment by csukuangfj** [comment]
@pzelasko 
Please install `kaldifeat` v1.8 from PyPI, i.e.,

```
pip install -v kaldifeat==1.8
```

---

Fixed and merged in https://github.com/csukuangfj/kaldifeat/pull/9
