### ISSUE TITLE
C++ 17 needed with torch 2.1

### ISSUE THREAD

**Issue by yuekaizhang** [csukuangfj/kaldifeat#80]
Seems that Pytorch 2.1 (current default version) compiled with C++ 17. So, https://github.com/csukuangfj/kaldifeat/blob/master/CMakeLists.txt#L35 this line may need to change to 17, otherwise, we can't install it from source.

Error: C++17 or later compatible compiler is required

**Comment by csukuangfj** [comment]
Please see https://github.com/csukuangfj/kaldifeat/pull/81

**Comment by yuekaizhang** [comment]
Thanks, but how do you fix it in 20 mins :D

**Comment by csukuangfj** [comment]
> Thanks, but how do you fix it in 20 mins :D

It has been fixed last week.

You can find pre-build wheels for torch 2.1 at 
https://csukuangfj.github.io/kaldifeat/cuda.html

**Comment by pzelasko** [comment]
It seems to still pop up, I'm adding python 3.12 and updating torch versions in Lhotse CI, unfortunately some configurations can't build, e.g.: https://github.com/lhotse-speech/lhotse/actions/runs/7888121954/job/21524871882?pr=1288
