### ISSUE TITLE
kaldifeat with torch2.3.0 support

### ISSUE THREAD

**Issue by kobenaxie** [csukuangfj/kaldifeat#97]
It seems there is no available whls for torch2.3.0 python 3.8 [here](https://[csukuangfj.github.io/kaldifeat/cuda.html](https://csukuangfj.github.io/kaldifeat/cuda.html))

**Comment by csukuangfj** [comment]
Please see

- https://csukuangfj.github.io/kaldifeat/cuda.html
- https://csukuangfj.github.io/kaldifeat/cpu.html
